# Permalinks
permalink:        pretty

# Setup
title:            Compagnie Saseo
tagline:          Cirque frénétique et tout terrain
description:      >
  Description...
url:              http://saseo.org
baseurl:          ""

paginate:         5

# Assets
sass:
 style:           :compressed

# About/contact
author:
  name:           'Thibaut Rizzi'

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

