# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Compagnie Saseo
tagline:          'Cirque frénétique et tout terrain'
description:      'Description...'
url:              http://saseo.org
baseurl:          /

author:
  name:           'Thibaut Rizzi'

paginate:         5

