# Permalinks
permalink:        pretty

# Setup
title:            SASEO
tagline:          La compagnie
description:      >
  Compagnie frénétique et tout terrain
url:              http://saseo.org
baseurl:          ""

# Assets
sass:
  style:           :compressed

# About/contact
author:
  name:           'Thibaut Rizzi'
